#!/usr/bin/env python3
"""Deterministic quality gates for intent-level paraphrases.

The module deliberately has no model or network dependency.  It is used both by
the paraphrase driver (cheap per-row feedback) and by ``ingest-paraphrase``
(authoritative per-row plus batch validation).  A failed candidate is never
rewritten into a transcription: callers quarantine it instead.
"""
from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from decimal import Decimal, InvalidOperation
import json
from pathlib import Path
import re
from typing import Any, Iterable


STOPWORD_NAMES = frozenset({
    "account", "address", "alert", "archive", "availability", "balance",
    "calendar", "client", "comment", "context", "detail", "document",
    "email", "estimate", "file", "filter", "history", "image", "item",
    "list", "location", "message", "note", "order", "page", "plan",
    "policy", "profile", "receipt", "record", "reference", "report",
    "request", "result", "route", "schedule", "service", "session",
    "setting", "shipment", "status", "summary", "tag", "task", "ticket",
    "timeline", "token", "topic", "transaction", "trip", "user", "value",
    "version", "window", "workflow",
})

_NUMBER_RE = re.compile(r"(?<![A-Za-z0-9_])[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?(?![A-Za-z0-9_])")
_QUOTED_RE = re.compile(r'"(?:\\.|[^"\\])*"')
_WORD_RE = re.compile(r"[A-Za-z0-9]+")


@dataclass
class GateResult:
    passed: bool
    failures: dict[str, list[str]] = field(default_factory=dict)

    def add(self, gate: str, detail: str) -> None:
        self.failures.setdefault(gate, []).append(detail)
        self.passed = False

    def as_dict(self) -> dict[str, Any]:
        return {"passed": self.passed, "failures": self.failures}


def canonical(value: Any) -> str:
    """Use the repository's JSON spelling without importing the GPU pipeline."""
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def normalize_identifier(value: str) -> str:
    return re.sub(r"[_\-.\s]", "", value.lower())


def _tokens(text: str, width: int) -> tuple[str, ...]:
    return tuple(word.lower() for word in _WORD_RE.findall(text))[:width]


def _style_name(value: Any) -> str:
    if isinstance(value, dict) and isinstance(value.get("name"), str):
        return value["name"]
    return str(value or "<missing>")


def _seed_values(seed: dict[str, Any]) -> list[tuple[Any, str | None]]:
    """Return values that are operationally supplied by the user.

    ``derived_values`` are intentionally omitted here: their values are
    generated by a previous tool call, but are added to the allowed creation
    set separately so quoting one cannot trigger a false invention failure.
    """
    derived = {(entry["stage"], entry["field"]) for entry in seed.get("derived_values", [])}
    values: list[tuple[Any, str | None]] = []
    seen: set[str] = set()
    for stage_index, stage in enumerate(seed.get("expected_stages", [])):
        for call in stage:
            tool = next((item for item in seed.get("tools", []) if item.get("name") == call.get("name")), {})
            properties = tool.get("parameters", {}).get("properties", {})
            for field_name, value in call.get("arguments", {}).items():
                if (stage_index, field_name) in derived:
                    continue
                key = canonical(value)
                if key not in seen:
                    values.append((value, properties.get(field_name, {}).get("type")))
                    seen.add(key)
    return values


def _all_known_values(seed: dict[str, Any]) -> list[Any]:
    values: list[Any] = []
    seen: set[str] = set()

    def add(value: Any) -> None:
        key = canonical(value)
        if key not in seen:
            values.append(value)
            seen.add(key)
        # A verbatim container literal necessarily surfaces its elements
        # (e.g. "tag-3" inside ["tag-3","tag-4"]), so they are not inventions.
        if isinstance(value, list):
            for item in value:
                add(item)
        elif isinstance(value, dict):
            for item in value.values():
                add(item)

    for stage in seed.get("expected_stages", []):
        for call in stage:
            for value in call.get("arguments", {}).values():
                add(value)
    return values


def _numeric_equivalent_present(text: str, value: Any) -> bool:
    try:
        expected = Decimal(str(value))
    except InvalidOperation:
        return False
    for token in _NUMBER_RE.findall(text):
        try:
            if Decimal(token) == expected:
                return True
        except InvalidOperation:
            continue
    return False


def check_schema_semantics(seed: dict[str, Any]) -> GateResult:
    result = GateResult(True)
    for tool in seed.get("tools", []):
        tool_name = str(tool.get("name", "<unnamed>"))
        for property_name, spec in tool.get("parameters", {}).get("properties", {}).items():
            description = spec.get("description")
            if not isinstance(description, str) or not description.strip():
                result.add("schema_semantics", f"{tool_name}.{property_name}: missing English description")
    return result


def check_typed_values(seed: dict[str, Any], request: str) -> GateResult:
    result = GateResult(True)
    for value, schema_type in _seed_values(seed):
        if schema_type in {"integer", "number"} and isinstance(value, (int, float)) and not isinstance(value, bool):
            if not _numeric_equivalent_present(request, value):
                result.add("typed_value_fidelity", f"missing numeric equivalent {canonical(value)}")
        elif canonical(value) not in request:
            result.add("typed_value_fidelity", f"missing verbatim literal {canonical(value)}")
    return result


def _internal_names(seed: dict[str, Any]) -> set[str]:
    names: set[str] = set()
    for tool in seed.get("tools", []):
        if isinstance(tool.get("name"), str):
            names.add(tool["name"])
        names.update(name for name in tool.get("parameters", {}).get("properties", {}) if isinstance(name, str))
    return {name for name in names if len(name) >= 4}


def check_schema_leaks(seed: dict[str, Any], request: str) -> GateResult:
    result = GateResult(True)
    collapsed_request = normalize_identifier(request)
    for name in sorted(_internal_names(seed)):
        # A literal API spelling is never acceptable, including ordinary words.
        if name in request:
            result.add("schema_derived_leak", f"exact internal name {name!r}")
            continue
        normalized = normalize_identifier(name)
        if normalized in STOPWORD_NAMES:
            continue
        if normalized and normalized in collapsed_request:
            result.add("schema_derived_leak", f"normalized internal name {name!r}")
    return result


def _strip_quoted(text: str) -> str:
    return _QUOTED_RE.sub(lambda match: " " * len(match.group(0)), text)


def check_operational_invention(seed: dict[str, Any], request: str) -> GateResult:
    result = GateResult(True)
    known_values = _all_known_values(seed)
    known_literals = {canonical(value) for value in known_values}
    known_numbers: set[Decimal] = set()
    for value in known_values:
        if isinstance(value, (int, float)) and not isinstance(value, bool):
            known_numbers.add(Decimal(str(value)))

    for quoted in _QUOTED_RE.findall(request):
        try:
            parsed = json.loads(quoted)
        except json.JSONDecodeError:
            continue
        if canonical(parsed) not in known_literals:
            result.add("operational_invention", f"unknown quoted literal {quoted}")

    for token in _NUMBER_RE.findall(_strip_quoted(request)):
        try:
            number = Decimal(token)
        except InvalidOperation:
            continue
        if number not in known_numbers:
            result.add("operational_invention", f"unknown numeric literal {token}")
    return result


def check_request(seed: dict[str, Any], request: Any) -> GateResult:
    result = GateResult(True)
    if not isinstance(request, str) or not request.strip():
        result.add("request", "request must be a non-empty string")
        return result
    for check in (check_schema_semantics, check_typed_values, check_schema_leaks, check_operational_invention):
        outcome = check(seed, request) if check is not check_schema_semantics else check(seed)
        for gate, details in outcome.failures.items():
            for detail in details:
                result.add(gate, detail)
    return result


def apply_batch_gates(rows: list[dict[str, Any]], results: list[GateResult]) -> None:
    """Reject batch-level quota violations and near-duplicate later candidates.

    Prefix/style quotas describe the submitted batch.  Every member of a
    violating group is rejected: retaining an arbitrary subset could make a
    passing row depend on JSONL ordering and does not prove the resulting set
    meets the advertised fraction.  Near-duplicate pairs retain the first row
    deterministically and reject later rows.
    """
    candidates = [(index, row) for index, row in enumerate(rows) if results[index].passed]
    total = len(candidates)
    if not total:
        return
    # The strictest quota is 10%; a batch smaller than ten cannot satisfy it
    # even when every request is unique.  Such smoke-sized inputs still receive
    # all per-row and duplicate checks, while production batches receive quotas.
    if total >= 10:
        buckets: dict[tuple[str, tuple[str, ...] | str], list[int]] = defaultdict(list)
        for index, row in candidates:
            request = row["natural_request"]
            buckets[("prefix2", _tokens(request, 2))].append(index)
            buckets[("prefix4", _tokens(request, 4))].append(index)
            buckets[("style", _style_name(row.get("style_card") or row.get("style")))].append(index)
        limits = {"prefix2": 0.25, "prefix4": 0.10, "style": 0.35}
        gate_names = {"prefix2": "batch_prefix_2", "prefix4": "batch_prefix_4", "style": "batch_style"}
        for (kind, key), indices in buckets.items():
            if len(indices) / total > limits[kind]:
                for index in indices:
                    results[index].add(gate_names[kind], f"{key!r}: {len(indices)}/{total}")

    accepted = [index for index, _row in candidates if results[index].passed]
    for position, index in enumerate(accepted):
        grams = _char_ngrams(rows[index]["natural_request"])
        for previous in accepted[:position]:
            other = _char_ngrams(rows[previous]["natural_request"])
            union = grams | other
            similarity = len(grams & other) / len(union) if union else 1.0
            if similarity >= 0.92:
                results[index].add("skeleton_similarity", f"duplicate of row {previous} (Jaccard={similarity:.3f})")
                break


def _char_ngrams(text: str) -> set[str]:
    normalized = re.sub(r"\s+", " ", text.lower()).strip()
    if len(normalized) < 3:
        return {normalized} if normalized else set()
    return {normalized[index:index + 3] for index in range(len(normalized) - 2)}


def evaluate_rows(seed_by_id: dict[str, dict[str, Any]], paraphrases: Iterable[dict[str, Any]], *, batch: bool) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    results: list[GateResult] = []
    for source in paraphrases:
        seed_id = source.get("seed_id")
        request = source.get("natural_request", source.get("paraphrase"))
        seed = seed_by_id.get(seed_id)
        result = GateResult(True) if seed is not None else GateResult(False, {"seed": ["unknown seed_id"]})
        if seed is not None:
            result = check_request(seed, request)
        rows.append({"seed_id": seed_id, "natural_request": request, "tier": source.get("tier", seed.get("tier") if seed else None),
                     "style_card": source.get("style_card", seed.get("style_card") if seed else None)})
        results.append(result)
    if batch:
        apply_batch_gates(rows, results)
    return [{**rows[index], **results[index].as_dict()} for index in range(len(rows))]


def _read_jsonl(path: Path) -> list[dict[str, Any]]:
    records = []
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if line.strip():
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError as exc:
                raise ValueError(f"invalid JSONL {path}:{line_number}") from exc
    return records


def shadow_report(records: list[dict[str, Any]]) -> dict[str, Any]:
    groups: dict[tuple[str, str], list[dict[str, Any]]] = defaultdict(list)
    for record in records:
        groups[(str(record.get("tier") or "<missing>"), _style_name(record.get("style_card")))].append(record)
    strata = {}
    for (tier, style), group in sorted(groups.items()):
        failures = Counter(gate for record in group for gate in record["failures"])
        strata[f"{tier}×{style}"] = {"n": len(group), "passed": sum(record["passed"] for record in group),
                                      "failed": sum(not record["passed"] for record in group),
                                      "fail_rates": {gate: count / len(group) for gate, count in sorted(failures.items())}}
    return {"schema_version": 1, "mode": "shadow", "rows": len(records), "strata": strata}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--shadow", action="store_true", help="report failures; never write or reject dataset rows")
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--paraphrases", required=True)
    parser.add_argument("--run-root", default=str(Path(__file__).resolve().parent / "data" / "selfgen_toolcall_intent_v1"))
    parser.add_argument("--out", help="optional JSON report path")
    args = parser.parse_args()
    if not args.shadow:
        parser.error("only --shadow is supported; authoritative rejection happens at ingest")
    frozen = json.loads((Path(args.run_root) / args.run_id / "seeds.json").read_text(encoding="utf-8"))
    seed_by_id = {seed["seed_id"]: seed for seed in frozen["seeds"]}
    report = shadow_report(evaluate_rows(seed_by_id, _read_jsonl(Path(args.paraphrases)), batch=True))
    rendered = json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True)
    if args.out:
        Path(args.out).write_text(rendered + "\n", encoding="utf-8")
    print(rendered)


if __name__ == "__main__":
    main()
