#!/usr/bin/env python3
"""Offline scaffolded self-generation pipeline for tool-calling data (v1).

The only external corpus consulted is the local Gorilla checkout.  Its BFCL
evaluation records are never emitted, sampled, or copied: their function
descriptions are reduced to aggregate structural statistics before seed creation.
Every retained conversation is generated by the true-stock k=8 model, selected
from four samples per assistant turn, and must pass JSON, schema, mock-executor,
plan-alignment, and contamination gates.  The training jsonl deliberately omits
the system prompt and few-shots used to produce the sample.
"""
from __future__ import annotations

import argparse
import copy
import datetime as dt
import hashlib
import json
import multiprocessing as mp
import os
from pathlib import Path
import queue
import random
import re
import subprocess
import sys
import time
import tomllib
import traceback
from collections import Counter
from dataclasses import dataclass
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[1]
ESFT = ROOT / "esft"
OUT_ROOT = ESFT / "data" / "selfgen_toolcall_v1"
GORILLA = ROOT / "external" / "gorilla" / "berkeley-function-call-leaderboard"
BFCL_DATA = GORILLA / "bfcl_eval" / "data"
ACE_CANDIDATES = (ROOT / "external" / "acebench", ROOT / "external" / "ACEBench")
MODEL_PATH = Path("/mnt/data/hf_cache/huggingface/hub/models--Qwen--Qwen3.6-35B-A3B/"
                  "snapshots/995ad96eacd98c81ed38be0c5b274b04031597b0")
STOCK_REVISION = "995ad96eacd98c81ed38be0c5b274b04031597b0"
PATTERNS = ("single", "parallel", "multi_turn", "error_recovery")
SCHEMA_COUNT = 197  # ~200, deliberately coprime with four pattern strata.
DOMAINS = (
    "clinic", "warehouse", "municipal", "library", "travel", "finance",
    "education", "energy", "agriculture", "media", "manufacturing", "retail",
    "logistics", "insurance", "hospitality", "research", "property", "events",
    "public_safety", "telecom",
)
WORKER_POLL_SECONDS = 1.0
NO_PROGRESS_WARNING_SECONDS = 300.0
WORKER_SENTINEL_GRACE_SECONDS = 5.0
TYPE_TEMPLATES: dict[str, list[tuple[str, list[Any] | None]]] = {
    "string": [("string", None)],
    "integer": [("integer", None)],
    "number": [("number", None)],
    "boolean": [("boolean", None)],
    "array": [("array", None)],
}


def canonical(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for block in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def atomic_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    tmp.replace(path)


def load_json_or_jsonl(path: Path) -> Any:
    """BFCL packages both JSON arrays and line-delimited .json files."""
    text = path.read_text(encoding="utf-8")
    try:
        return json.loads(text)
    except json.JSONDecodeError as array_error:
        rows = []
        try:
            for line in text.splitlines():
                if line.strip():
                    rows.append(json.loads(line))
        except json.JSONDecodeError:
            raise array_error
        if not rows:
            raise array_error
        return rows


def atomic_jsonl(path: Path, rows: Iterable[dict[str, Any]]) -> None:
    """Write a completed corpus atomically so a resumed execute cannot duplicate it."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8") as fh:
        for row in rows:
            fh.write(canonical(row) + "\n")
        fh.flush()
        os.fsync(fh.fileno())
    tmp.replace(path)


def normal_tokens(value: Any) -> list[str]:
    return re.findall(r"[a-z0-9]+", str(value).lower().replace("_", " "))


def ngrams(value: Any, n: int = 8) -> set[tuple[str, ...]]:
    toks = normal_tokens(value)
    return {tuple(toks[i:i + n]) for i in range(max(0, len(toks) - n + 1))}


def value_for(prop: dict[str, Any], index: int) -> Any:
    if "enum" in prop:
        return prop["enum"][index % len(prop["enum"])]
    kind = prop["type"]
    if kind == "string":
        return f"item-{index + 17}"
    if kind == "integer":
        return index + 2
    if kind == "number":
        return round(index + 0.75, 2)
    if kind == "boolean":
        return bool(index % 2)
    if kind == "array":
        return [f"tag-{index + 1}", f"tag-{index + 2}"]
    raise ValueError(f"unsupported type {kind}")


def validate_value(value: Any, spec: dict[str, Any]) -> str | None:
    kind = spec.get("type")
    if kind == "string" and not isinstance(value, str):
        return "type_string"
    if kind == "integer" and (not isinstance(value, int) or isinstance(value, bool)):
        return "type_integer"
    if kind == "number" and (not isinstance(value, (int, float)) or isinstance(value, bool)):
        return "type_number"
    if kind == "boolean" and not isinstance(value, bool):
        return "type_boolean"
    if kind == "array":
        if not isinstance(value, list) or not all(isinstance(x, str) for x in value):
            return "type_array"
    if "enum" in spec and value not in spec["enum"]:
        return "enum"
    return None


def validate_call(call: Any, tools: dict[str, dict[str, Any]]) -> tuple[str | None, dict[str, Any] | None]:
    if not isinstance(call, dict) or set(call) != {"name", "arguments"}:
        return "call_shape", None
    name, args = call["name"], call["arguments"]
    if not isinstance(name, str) or name not in tools:
        return "undeclared_function", None
    if not isinstance(args, dict):
        return "arguments_not_object", None
    params = tools[name]["parameters"]
    props, required = params["properties"], set(params["required"])
    if set(args) - set(props):
        return "unknown_argument", None
    if required - set(args):
        return "missing_required", None
    for key, value in args.items():
        error = validate_value(value, props[key])
        if error:
            return f"{error}:{key}", None
    return None, {"name": name, "arguments": args}


def extract_json(text: str) -> tuple[Any | None, str | None]:
    """Accept one JSON object, optionally fenced; no repair beyond fencing."""
    stripped = text.strip()
    if stripped.startswith("```"):
        m = re.fullmatch(r"```(?:json)?\s*(.*?)\s*```", stripped, flags=re.S | re.I)
        if not m:
            return None, "json_fence"
        stripped = m.group(1)
    try:
        return json.loads(stripped), None
    except json.JSONDecodeError:
        return None, "json_parse"


def parse_model_turn(text: str, tools: dict[str, dict[str, Any]]) -> tuple[list[dict[str, Any]] | None, str | None]:
    payload, error = extract_json(text)
    if error:
        return None, error
    if not isinstance(payload, dict) or set(payload) != {"calls"} or not isinstance(payload["calls"], list):
        return None, "turn_shape"
    if not payload["calls"]:
        return None, "empty_calls"
    calls = []
    for call in payload["calls"]:
        error, normalized = validate_call(call, tools)
        if error:
            return None, error
        assert normalized is not None
        calls.append(normalized)
    if len({canonical(x) for x in calls}) != len(calls):
        return None, "duplicate_call"
    return calls, None


def bfcl_structural_profile() -> dict[str, Any]:
    """Reduce BFCL evaluation schemas to statistics; retain neither task nor API text."""
    if not BFCL_DATA.is_dir():
        return {"available": False, "reason": f"missing {BFCL_DATA}"}
    arities: list[int] = []
    type_counts: Counter[str] = Counter()
    files: dict[str, str] = {}
    for path in sorted(BFCL_DATA.glob("BFCL_v4_*.json")):
        rows = load_json_or_jsonl(path)
        if not isinstance(rows, list):
            continue
        files[str(path.relative_to(ROOT))] = sha256(path)
        for row in rows:
            if not isinstance(row, dict):
                # Some auxiliary BFCL files are scalar metadata rather than
                # evaluation records.  They contribute no schema statistics.
                continue
            for fn in row.get("function", []):
                # Function documentation is traversed only long enough to count
                # parameters/types.  Names, descriptions, and examples do not escape.
                params = fn.get("parameters", {}) if isinstance(fn, dict) else {}
                props = params.get("properties", {}) if isinstance(params, dict) else {}
                arities.append(len(props))
                for prop in props.values():
                    if isinstance(prop, dict):
                        raw = prop.get("type", "unknown")
                        type_counts[raw if isinstance(raw, str) else "union"] += 1
    return {
        "available": True,
        "method": "aggregate arity/type counts only; no BFCL content retained",
        "files_sha256": files,
        "function_count": len(arities),
        "arity_histogram": dict(sorted(Counter(arities).items())),
        "type_histogram": dict(sorted(type_counts.items())),
    }


def contamination_corpus() -> tuple[dict[str, Any], set[tuple[str, ...]], set[str]]:
    """Load local eval text solely for rejection, including ACEBench if present."""
    sources: list[Path] = []
    if BFCL_DATA.is_dir():
        sources.extend(sorted(BFCL_DATA.glob("BFCL_v4_*.json")))
    ace_roots = [p for p in ACE_CANDIDATES if p.exists()]
    for root in ace_roots:
        sources.extend(sorted(p for p in root.rglob("*") if p.suffix.lower() in {".json", ".jsonl"}))
    grams: set[tuple[str, ...]] = set()
    names: set[str] = set()
    hashes: dict[str, str] = {}
    def visit(x: Any) -> None:
        if isinstance(x, dict):
            for key, value in x.items():
                if key in {"name", "function_name"} and isinstance(value, str):
                    names.add(value.lower())
                visit(value)
        elif isinstance(x, list):
            for value in x:
                visit(value)
        elif isinstance(x, str):
            grams.update(ngrams(x))
    for path in sources:
        hashes[str(path.relative_to(ROOT))] = sha256(path)
        try:
            visit(load_json_or_jsonl(path))
        except (OSError, UnicodeDecodeError, json.JSONDecodeError):
            # A malformed local source must be visible in the manifest but cannot
            # quietly turn into copied output.
            raise RuntimeError(f"cannot parse contamination source {path}")
    return ({
        "method": "reject exact normalized 8-gram overlap or evaluator function-name collision",
        "bfcl_sources": sum(1 for p in sources if "BFCL_v4_" in p.name),
        "acebench_roots": [str(p.relative_to(ROOT)) for p in ace_roots],
        "acebench_present": bool(ace_roots),
        "source_sha256": hashes,
        "ngram_size": 8,
    }, grams, names)


def contaminated(seed: dict[str, Any], eval_grams: set[tuple[str, ...]], eval_names: set[str]) -> str | None:
    schema_names = {tool["name"].lower() for tool in seed["tools"]}
    if schema_names & eval_names:
        return "contamination_function_name"
    projection = {"request": seed["user_request"], "tools": seed["tools"]}
    if ngrams(canonical(projection)) & eval_grams:
        return "contamination_8gram"
    return None


def property_spec(slot: int, rng: random.Random) -> dict[str, Any]:
    kinds = ("string", "integer", "number", "boolean", "array")
    kind = kinds[(slot + rng.randrange(len(kinds))) % len(kinds)]
    out: dict[str, Any] = {"type": kind}
    if kind == "string" and slot % 3 == 0:
        out["enum"] = [f"mode-{slot}-a", f"mode-{slot}-b", f"mode-{slot}-c"]
    if kind == "array":
        out["items"] = {"type": "string"}
    return out


def build_tool(domain: str, seed_id: int, ordinal: int, rng: random.Random) -> dict[str, Any]:
    action = ("inspect", "list", "reserve", "update", "search", "estimate", "schedule")[ordinal % 7]
    count = 2 + ((seed_id + ordinal) % 3)
    props: dict[str, dict[str, Any]] = {}
    for j in range(count):
        props[f"field_{ordinal + 1}_{j + 1}"] = property_spec(seed_id + j + ordinal, rng)
    required = list(props)[:2 + ((seed_id + ordinal) % max(1, count - 1))]
    return {
        "type": "function",
        "name": f"mock_{domain}_{seed_id:03d}_{action}_{ordinal + 1}",
        "description": f"Synthetic {domain} operation {ordinal + 1}; offline mock only.",
        "parameters": {"type": "object", "properties": props, "required": required,
                       "additionalProperties": False},
    }


def require_link_field(tool: dict[str, Any], name: str, spec: dict[str, Any]) -> None:
    """Make a mock-executor result dependency explicit in a follow-up schema."""
    params = tool["parameters"]
    params["properties"][name] = spec
    params["required"].append(name)


def expected_call(tool: dict[str, Any], nonce: int) -> dict[str, Any]:
    props = tool["parameters"]["properties"]
    args = {name: value_for(spec, nonce + pos) for pos, (name, spec) in enumerate(props.items())
            if name in tool["parameters"]["required"]}
    return {"name": tool["name"], "arguments": args}


def call_request_fragment(call: dict[str, Any], *, omit: set[str] | None = None) -> str:
    omit = omit or set()
    values = "; ".join(f"{key}={canonical(value)}" for key, value in call["arguments"].items()
                       if key not in omit)
    return f"call {call['name']} with {values}"


def make_seed(seed_id: int, rng: random.Random) -> dict[str, Any]:
    schema_id = seed_id % SCHEMA_COUNT
    domain = DOMAINS[schema_id % len(DOMAINS)]
    pattern = PATTERNS[seed_id % len(PATTERNS)]
    tools = [build_tool(domain, schema_id, i, rng) for i in range(3)]
    if pattern == "single":
        stages = [[expected_call(tools[0], seed_id)]]
        request = f"For this {domain} request, {call_request_fragment(stages[0][0])}."
    elif pattern == "parallel":
        stages = [[expected_call(tools[0], seed_id), expected_call(tools[1], seed_id + 11)]]
        request = (f"For this {domain} request, independently and in parallel, "
                   f"{call_request_fragment(stages[0][0])}; also {call_request_fragment(stages[0][1])}.")
    elif pattern == "multi_turn":
        first = expected_call(tools[0], seed_id)
        receipt = mock_execute(first, 0, pattern)["result"]["receipt"]
        require_link_field(tools[1], "prior_receipt", {"type": "string"})
        second = expected_call(tools[1], seed_id + 19)
        second["arguments"]["prior_receipt"] = receipt
        stages = [[first], [second]]
        request = (f"For this {domain} request, first {call_request_fragment(first)}. After its tool result, "
                   f"{call_request_fragment(second, omit={'prior_receipt'})}, and set prior_receipt to the "
                   "receipt returned by the first tool.")
    else:
        first = expected_call(tools[0], seed_id)
        require_link_field(tools[2], "recovery_code", {"type": "string", "enum": ["UNAVAILABLE"]})
        second = expected_call(tools[2], seed_id + 29)
        second["arguments"]["recovery_code"] = "UNAVAILABLE"
        stages = [[first], [second]]
        request = (f"For this {domain} request, first {call_request_fragment(first)}. If it returns an error, "
                   f"recover by {call_request_fragment(second, omit={'recovery_code'})} and set recovery_code "
                   "to the returned error code.")
    return {"seed_id": f"seed-{seed_id:04d}", "schema_id": f"schema-{schema_id:03d}",
            "domain": domain, "pattern": pattern,
            "tools": tools, "user_request": request, "expected_stages": stages}


def build_seeds(count: int, rng_seed: int, profile: dict[str, Any],
                eval_grams: set[tuple[str, ...]], eval_names: set[str]) -> tuple[list[dict[str, Any]], Counter[str]]:
    # Domain/pattern are round-robin: requested strata are balanced before model output.
    rng = random.Random(rng_seed)
    seeds, rejected = [], Counter()
    candidate = 0
    while len(seeds) < count:
        seed = make_seed(candidate, rng)
        reason = contaminated(seed, eval_grams, eval_names)
        if reason:
            rejected[reason] += 1
        else:
            seed["structure_reference"] = {
                "bfcl_function_count": profile.get("function_count", 0),
                "bfcl_arity_histogram": profile.get("arity_histogram", {}),
            }
            seeds.append(seed)
        candidate += 1
        if candidate > count * 20:
            raise RuntimeError("contamination filter excluded too many generated seeds")
    return seeds, rejected


def mock_execute(call: dict[str, Any], stage: int, pattern: str) -> dict[str, Any]:
    """Deterministic API result; executor is never allowed to make network calls."""
    if pattern == "error_recovery" and stage == 0:
        return {"ok": False, "error": {"code": "UNAVAILABLE", "retryable": True},
                "call": call["name"]}
    digest = hashlib.sha256(canonical(call).encode()).hexdigest()[:12]
    return {"ok": True, "result": {"receipt": f"mock-{digest}", "stage": stage + 1},
            "call": call["name"]}


SYSTEM = """You are a precise offline tool-calling assistant. Use only declared tools.
Return exactly one JSON object, no prose and no Markdown: {\"calls\":[{\"name\":...,\"arguments\":{...}}]}.
Every call must use all required fields with values that satisfy the JSON schema.
For recovery, read the tool result and choose the declared fallback. Do not invent tools."""
FEW_SHOTS = [
    {"user": "Schema: mock_catalog.inspect requires item_id string. Request: inspect item.",
     "assistant": {"calls": [{"name": "mock_catalog.inspect", "arguments": {"item_id": "item-17"}}]}},
    {"user": "Schema: mock_a.list and mock_b.list each require group string. Request: check both.",
     "assistant": {"calls": [{"name": "mock_a.list", "arguments": {"group": "item-3"}}, {"name": "mock_b.list", "arguments": {"group": "item-4"}}]}},
    {"user": "Schema: mock_primary.lookup and mock_fallback.search. Result: UNAVAILABLE. Request: recover.",
     "assistant": {"calls": [{"name": "mock_fallback.search", "arguments": {"query": "item-9"}}]}},
]


def scaffold_prompt(seed: dict[str, Any], stage: int, tool_results: list[dict[str, Any]]) -> str:
    # This material is input-only scaffolding.  It is never written into train.jsonl.
    return canonical({"system": SYSTEM, "few_shots": FEW_SHOTS, "tools": seed["tools"],
                      "user_request": seed["user_request"], "turn": stage + 1,
                      "prior_tool_results": tool_results,
                      "instruction": "Emit the next assistant tool-call JSON only."})


def render_training(seed: dict[str, Any], selected: list[list[dict[str, Any]]],
                    results: list[list[dict[str, Any]]]) -> dict[str, Any]:
    messages: list[dict[str, Any]] = [{"role": "user", "content": seed["user_request"]}]
    for calls, stage_results in zip(selected, results):
        messages.append({"role": "assistant", "content": None,
                         "tool_calls": [{"type": "function", "function": {
                             "name": call["name"], "arguments": canonical(call["arguments"]),
                         }} for call in calls]})
        for call, result in zip(calls, stage_results):
            messages.append({"role": "tool", "name": call["name"], "content": canonical(result)})
    # Schemas are task context, while system instruction/few-shots are removed.
    return {"tools": seed["tools"], "messages": messages}


def select_candidate(raws: list[str], expected: list[dict[str, Any]], tools: dict[str, dict[str, Any]]) -> tuple[list[dict[str, Any]] | None, list[str], int | None]:
    reasons = []
    for index, raw in enumerate(raws):
        calls, reason = parse_model_turn(raw, tools)
        if reason:
            reasons.append(reason)
            continue
        if canonical(calls) != canonical(expected):
            reasons.append("plan_alignment")
            continue
        return calls, reasons, index
    return None, reasons or ["no_candidate"], None


@dataclass
class GenerationSpec:
    seed: int
    temperature: float
    max_new: int
    best_of: int
    gpu: int


def load_stock_model(gpu: int):
    import torch
    sys.path.insert(0, str(ESFT))
    from eval_harness import resolve_model_spec, load_subject_model
    spec = resolve_model_spec("base", model_path=str(MODEL_PATH), topk=8)
    torch.cuda.set_device(gpu)
    tokenizer, model, _ = load_subject_model(spec, gpu)
    return torch, tokenizer, model


def generate_candidates(torch: Any, tokenizer: Any, model: Any, prompt: str,
                        spec: GenerationSpec) -> list[str]:
    enc = tokenizer(prompt, return_tensors="pt", add_special_tokens=False).to(f"cuda:{spec.gpu}")
    input_len = enc["input_ids"].shape[1]
    with torch.no_grad():
        generated = model.generate(**enc, max_new_tokens=spec.max_new, do_sample=True,
                                   temperature=spec.temperature, top_p=0.95,
                                   num_return_sequences=spec.best_of,
                                   pad_token_id=tokenizer.pad_token_id)
    return [tokenizer.decode(row[input_len:], skip_special_tokens=True) for row in generated]


def checkpoint_path(target: Path, gpu: int) -> Path:
    return target / f"generation_records_gpu{gpu}.jsonl"


def append_checkpoint_record(path: Path, record: dict[str, Any]) -> None:
    """Durably commit one finished task before considering it resumable."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as fh:
        fh.write(canonical(record) + "\n")
        fh.flush()
        os.fsync(fh.fileno())


def load_checkpoint_records(target: Path, seeds: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Load and validate durable task checkpoints from a prior interrupted execute."""
    expected = {seed["seed_id"]: seed for seed in seeds}
    if len(expected) != len(seeds):
        raise RuntimeError("prepared seeds contain duplicate seed IDs")
    records: dict[str, dict[str, Any]] = {}
    for gpu in (0, 1):
        path = checkpoint_path(target, gpu)
        if not path.exists():
            continue
        with path.open(encoding="utf-8") as fh:
            for line_number, line in enumerate(fh, 1):
                if not line.strip():
                    continue
                try:
                    record = json.loads(line)
                    seed = record["seed"]
                    seed_id = seed["seed_id"]
                except (json.JSONDecodeError, KeyError, TypeError) as exc:
                    raise RuntimeError(f"invalid checkpoint {path.name}:{line_number}: {exc}") from exc
                if seed_id not in expected:
                    raise RuntimeError(f"checkpoint {path.name}:{line_number} has unknown task ID {seed_id!r}")
                if canonical(seed) != canonical(expected[seed_id]):
                    raise RuntimeError(f"checkpoint {path.name}:{line_number} does not match frozen seed {seed_id!r}")
                if seed_id in records:
                    raise RuntimeError(f"duplicate completed task ID {seed_id!r} in checkpoints")
                records[seed_id] = record
    return records


def pending_seeds(seeds: list[dict[str, Any]], completed: dict[str, dict[str, Any]]) -> list[dict[str, Any]]:
    return [seed for seed in seeds if seed["seed_id"] not in completed]


def generation_worker(gpu: int, seeds: list[dict[str, Any]], spec: GenerationSpec,
                      checkpoint: Path, output: mp.Queue) -> None:
    try:
        torch, tokenizer, model = load_stock_model(gpu)
        for num, seed in enumerate(seeds, 1):
            tool_map = {tool["name"]: tool for tool in seed["tools"]}
            selected, all_results, selections, failures = [], [], [], []
            prior_results: list[dict[str, Any]] = []
            for stage, expected in enumerate(seed["expected_stages"]):
                raws = generate_candidates(torch, tokenizer, model, scaffold_prompt(seed, stage, prior_results), spec)
                calls, reasons, chosen = select_candidate(raws, expected, tool_map)
                if calls is None:
                    failures.extend(reasons)
                    # Diagnostics only: keep the raw candidates of a failed stage so the
                    # reject reason can be inspected post hoc. Off by default.
                    if os.environ.get("SELFGEN_DEBUG_RAW") == "1":
                        debug = checkpoint.parent / f"debug_failures_gpu{gpu}.jsonl"
                        with debug.open("a", encoding="utf-8") as fh:
                            fh.write(json.dumps(
                                {"seed_id": seed["seed_id"], "pattern": seed["pattern"],
                                 "stage": stage, "reasons": reasons, "raws": raws},
                                ensure_ascii=False) + "\n")
                    break
                results = [mock_execute(call, stage, seed["pattern"]) for call in calls]
                selected.append(calls)
                all_results.append(results)
                selections.append({"stage": stage, "candidate_index": chosen,
                                   "candidate_rejections": reasons})
                prior_results.extend(results)
            record = {"seed": seed, "selected": selected, "results": all_results,
                      "selection": selections, "failures": failures}
            append_checkpoint_record(checkpoint, record)
            print(f"[selfgen gpu{gpu}] {num}/{len(seeds)}", flush=True)
        output.put({"kind": "complete", "gpu": gpu, "records_written": len(seeds)})
    except BaseException as exc:
        output.put({"kind": "error", "gpu": gpu,
                    "error": f"{type(exc).__name__}: {exc}", "traceback": traceback.format_exc()})


def wait_for_worker_completion(workers: list[mp.Process], output: mp.Queue) -> None:
    """Wait indefinitely for terminal worker sentinels while still detecting dead workers."""
    pending = {worker.pid: worker for worker in workers}
    gpu_by_pid = {worker.pid: gpu for gpu, worker in zip((0, 1), workers)}
    last_progress = time.monotonic()
    dead_since: dict[int | None, float] = {}
    while pending:
        try:
            item = output.get_nowait()
        except queue.Empty:
            now = time.monotonic()
            dead = []
            for pid, worker in pending.items():
                if worker.is_alive():
                    dead_since.pop(pid, None)
                    continue
                dead_since.setdefault(pid, now)
                dead.append((pid, gpu_by_pid[pid], worker.exitcode))
            if dead and all(now - dead_since[pid] >= WORKER_SENTINEL_GRACE_SECONDS
                            for pid, _, _ in dead):
                details = ", ".join(f"gpu{gpu} exitcode={exitcode}" for _, gpu, exitcode in dead)
                all_workers_dead = len(dead) == len(pending)
                print(f"[selfgen] worker terminal sentinel missing ({details}; "
                      f"all_workers_dead={all_workers_dead})", flush=True)
                raise RuntimeError(f"generation worker exited without reporting completion: {details}")
            if now - last_progress >= NO_PROGRESS_WARNING_SECONDS:
                live = [f"gpu{gpu_by_pid[pid]} pid={worker.pid}" for pid, worker in pending.items()
                        if worker.is_alive()]
                print(f"[selfgen] no worker terminal progress for "
                      f"{int(now - last_progress)}s; waiting for {', '.join(live) or 'none'}", flush=True)
                last_progress = now
            time.sleep(WORKER_POLL_SECONDS)
            continue
        last_progress = time.monotonic()
        if not isinstance(item, dict) or "gpu" not in item:
            raise RuntimeError(f"invalid generation worker sentinel: {item!r}")
        gpu = item["gpu"]
        matching = [pid for pid, expected_gpu in gpu_by_pid.items() if expected_gpu == gpu]
        if len(matching) != 1 or matching[0] not in pending:
            raise RuntimeError(f"unexpected or duplicate generation worker sentinel for GPU {gpu!r}")
        pid = matching[0]
        if item.get("kind") == "error":
            detail = item.get("error", "unknown worker error")
            worker_traceback = item.get("traceback", "")
            print(f"[selfgen] GPU {gpu} worker exception: {detail}\n{worker_traceback}", flush=True)
            raise RuntimeError(f"GPU {gpu} worker failed: {detail}")
        if item.get("kind") != "complete":
            raise RuntimeError(f"invalid generation worker sentinel for GPU {gpu}: {item!r}")
        del pending[pid]


def cpu_fixture_records(seeds: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Deterministic validator fixture, explicitly not a model-generated corpus."""
    records = []
    for seed in seeds:
        selected = copy.deepcopy(seed["expected_stages"])
        results = [[mock_execute(call, stage, seed["pattern"]) for call in calls]
                   for stage, calls in enumerate(selected)]
        records.append({"seed": seed, "selected": selected, "results": results,
                        "selection": [{"stage": i, "candidate_index": 0,
                                       "candidate_rejections": []} for i in range(len(selected))],
                        "failures": []})
    return records


def evaluate_records(records: list[dict[str, Any]], eval_grams: set[tuple[str, ...]],
                     eval_names: set[str]) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Counter[str]]:
    accepted, rejected, reasons = [], [], Counter()
    for record in records:
        seed = record["seed"]
        failure = contaminated(seed, eval_grams, eval_names)
        if not failure and record["failures"]:
            failure = record["failures"][0]
        tool_map = {tool["name"]: tool for tool in seed["tools"]}
        if not failure:
            if len(record["selected"]) != len(seed["expected_stages"]):
                failure = "incomplete_dialogue"
            else:
                for stage, (calls, expected, stage_results) in enumerate(zip(
                        record["selected"], seed["expected_stages"], record["results"])):
                    if canonical(calls) != canonical(expected):
                        failure = "plan_alignment"
                        break
                    if len(calls) != len(stage_results):
                        failure = "executor_cardinality"
                        break
                    for call, result in zip(calls, stage_results):
                        err, _ = validate_call(call, tool_map)
                        if err:
                            failure = err
                            break
                        if result != mock_execute(call, stage, seed["pattern"]):
                            failure = "executor_inconsistent"
                            break
                    if not failure and stage > 0:
                        prior = record["results"][stage - 1][0]
                        if seed["pattern"] == "multi_turn":
                            if calls[0]["arguments"].get("prior_receipt") != prior.get("result", {}).get("receipt"):
                                failure = "multi_turn_result_mismatch"
                        elif seed["pattern"] == "error_recovery":
                            if calls[0]["arguments"].get("recovery_code") != prior.get("error", {}).get("code"):
                                failure = "error_recovery_mismatch"
                    if failure:
                        break
        meta = {"id": seed["seed_id"], "domain": seed["domain"], "pattern": seed["pattern"],
                "schema_sha256": hashlib.sha256(canonical(seed["tools"]).encode()).hexdigest(),
                "best_of": 4, "selection": record["selection"],
                "validator": {"json": True, "schema": not failure, "executor": not failure,
                              "multi_turn": not failure, "contamination": not failure}}
        if failure:
            reasons[failure] += 1
            rejected.append({"id": seed["seed_id"], "reason": failure, "seed": seed,
                             "selection": record["selection"]})
        else:
            accepted.append({**render_training(seed, record["selected"], record["results"]), "metadata": meta})
    return accepted, rejected, reasons


def run_dir(run_id: str) -> Path:
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_.-]*", run_id):
        raise ValueError("run_id must be safe filename characters")
    return OUT_ROOT / run_id


def verified_stock_identity() -> dict[str, Any]:
    """Reuse the campaign fingerprint check without touching any B2 artifact."""
    with (ESFT / "codex_harness.toml").open("rb") as fh:
        cfg = tomllib.load(fh)
    stock = cfg.get("stock", {})
    if stock.get("revision") != STOCK_REVISION or stock.get("path") != str(MODEL_PATH):
        raise RuntimeError("codex_harness stock config is not the declared true-stock snapshot")
    sys.path.insert(0, str(ESFT))
    from codex_harness import stock_identity
    return stock_identity(stock)


def gpu_preflight(run_id: str) -> dict[str, Any]:
    """Fail closed before CUDA loading; only physical GPU 0/1 are eligible."""
    target = run_dir(run_id)
    manifest = json.loads((target / "manifest.json").read_text(encoding="utf-8"))
    if manifest.get("state") != "prepared":
        raise RuntimeError(f"run state must be prepared, got {manifest.get('state')!r}")
    if manifest.get("model") != {"identity": verified_stock_identity(), "topk": 8, "patch": None}:
        raise RuntimeError("true-stock identity changed since preparation")
    proc = subprocess.run(
        ["nvidia-smi", "--query-gpu=index,name,memory.used,utilization.gpu", "--format=csv,noheader,nounits"],
        text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=False)
    if proc.returncode != 0:
        raise RuntimeError(f"GPU preflight failed: nvidia-smi exit {proc.returncode}: {proc.stdout.strip()}")
    rows = []
    for line in proc.stdout.splitlines():
        parts = [x.strip() for x in line.split(",")]
        if len(parts) != 4:
            raise RuntimeError(f"unexpected nvidia-smi row: {line!r}")
        rows.append({"index": int(parts[0]), "name": parts[1], "memory_used_mib": int(parts[2]),
                     "utilization_percent": int(parts[3])})
    by_id = {row["index"]: row for row in rows}
    if not {0, 1}.issubset(by_id) or 2 not in by_id:
        raise RuntimeError("expected local physical GPUs 0, 1, and display GPU 2")
    busy = [by_id[i] for i in (0, 1)
            if by_id[i]["memory_used_mib"] > 1024 or by_id[i]["utilization_percent"] > 5]
    if busy:
        raise RuntimeError(f"GPU 0/1 are busy: {busy}")
    result = {"checked_at": dt.datetime.now(dt.UTC).isoformat(), "run_id": run_id,
              "allowed_physical_gpus": [0, 1], "forbidden_display_gpu": 2, "gpus": rows,
              "stock": manifest["model"]["identity"], "result": "PASS"}
    atomic_json(target / f"preflight_{dt.datetime.now(dt.UTC).strftime('%Y%m%dT%H%M%SZ')}.json", result)
    return result


def prepare(args: argparse.Namespace) -> None:
    target = run_dir(args.run_id)
    if target.exists():
        raise FileExistsError(f"refusing to overwrite {target}")
    stock = verified_stock_identity()
    profile = bfcl_structural_profile()
    contamination, eval_grams, eval_names = contamination_corpus()
    seeds, rejected = build_seeds(args.n, args.seed, profile, eval_grams, eval_names)
    target.mkdir(parents=True)
    atomic_json(target / "seeds.json", {"schema_version": 1, "created_at": dt.datetime.now(dt.UTC).isoformat(),
                                         "rng_seed": args.seed, "count": args.n, "bfcl_structure": profile,
                                         "contamination": contamination, "seed_filter_rejections": dict(rejected),
                                         "seeds": seeds})
    atomic_json(target / "manifest.json", {"schema_version": 1, "run_id": args.run_id,
                                             "state": "prepared", "created_at": dt.datetime.now(dt.UTC).isoformat(),
                                             "model": {"identity": stock, "topk": 8, "patch": None},
                                             "generation": {"gpus": [0, 1], "best_of": args.best_of,
                                                            "temperature": args.temperature, "max_new": args.max_new},
                                             "strata": {"patterns": list(PATTERNS), "domains": list(DOMAINS),
                                                         "schema_count": SCHEMA_COUNT, "recursion_rounds": 1},
                                             "contamination": contamination,
                                             "artifacts": {"seeds": "seeds.json",
                                                           "generation_checkpoints": [
                                                               "generation_records_gpu0.jsonl",
                                                               "generation_records_gpu1.jsonl"]}})
    print(target)


def execute(args: argparse.Namespace) -> None:
    target = run_dir(args.run_id)
    manifest_path, seeds_path = target / "manifest.json", target / "seeds.json"
    if not manifest_path.is_file() or not seeds_path.is_file():
        raise FileNotFoundError("run must be prepared first")
    manifest, frozen = json.loads(manifest_path.read_text()), json.loads(seeds_path.read_text())
    if manifest["state"] != "prepared":
        raise RuntimeError(f"run state must be prepared, got {manifest['state']}")
    if manifest["model"] != {"identity": verified_stock_identity(), "topk": 8, "patch": None}:
        raise RuntimeError("true-stock k8 identity in manifest changed")
    # The 500-sample production run must actually be model generated; fixture is
    # solely for CPU verification and stamps a non-training artifact.
    if args.fixture:
        records = cpu_fixture_records(frozen["seeds"])
        atomic_json(target / "fixture_validation.json", {"not_training_data": True, "records": records})
    else:
        completed = load_checkpoint_records(target, frozen["seeds"])
        todo = pending_seeds(frozen["seeds"], completed)
        print(f"[selfgen] resuming {args.run_id}: {len(completed)} completed, {len(todo)} pending", flush=True)
        if todo:
            gpu_preflight(args.run_id)
            by_gpu = {0: todo[0::2], 1: todo[1::2]}
            output: mp.Queue = mp.Queue()
            workers = [mp.Process(target=generation_worker, args=(gpu, by_gpu[gpu],
                       GenerationSpec(args.seed, args.temperature, args.max_new, args.best_of, gpu),
                       checkpoint_path(target, gpu), output))
                       for gpu in (0, 1)]
            for worker in workers:
                worker.start()
            try:
                wait_for_worker_completion(workers, output)
            finally:
                for worker in workers:
                    if worker.is_alive():
                        worker.terminate()
                    worker.join(timeout=30)
                output.close()
                output.join_thread()
        records = list(load_checkpoint_records(target, frozen["seeds"]).values())
        records.sort(key=lambda record: record["seed"]["seed_id"])
        if len(records) != len(frozen["seeds"]):
            raise RuntimeError("missing generated records")
    contamination, grams, names = contamination_corpus()
    accepted, rejected, reasons = evaluate_records(records, grams, names)
    if args.fixture:
        # Fixture proves validation only; never make it look like a corpus.
        atomic_json(target / "fixture_summary.json", {"accepted": len(accepted), "rejected": len(rejected),
                                                       "reason_counts": dict(reasons)})
        print("fixture validation passed; no training jsonl written")
        return
    atomic_jsonl(target / "train.jsonl", accepted)
    atomic_jsonl(target / "rejected.jsonl", rejected)
    summary = {"schema_version": 1, "run_id": args.run_id, "completed_at": dt.datetime.now(dt.UTC).isoformat(),
               "generated": len(records), "accepted": len(accepted), "rejected": len(rejected),
               "acceptance_rate": len(accepted) / len(records) if records else 0.0,
               "rejection_reasons": dict(reasons), "strata": {
                   "generated": {k: sum(r["seed"]["pattern"] == k for r in records) for k in PATTERNS},
                   "accepted": {k: sum(x["metadata"]["pattern"] == k for x in accepted) for k in PATTERNS}},
               "truncation_count": 0, "contamination": contamination}
    atomic_json(target / "summary.json", summary)
    manifest["state"] = "completed"
    # jobEvents' local-manifest watcher uses this established terminal marker.
    manifest["status"] = "complete"
    manifest["completed_at"] = summary["completed_at"]
    manifest["artifacts"].update({
        "generation_checkpoints": ["generation_records_gpu0.jsonl", "generation_records_gpu1.jsonl"],
        "train": "train.jsonl", "rejected": "rejected.jsonl", "summary": "summary.json"})
    atomic_json(manifest_path, manifest)
    print(canonical(summary))


def preflight(args: argparse.Namespace) -> None:
    print(json.dumps(gpu_preflight(args.run_id), ensure_ascii=False, indent=2))


def parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__)
    sub = p.add_subparsers(required=True)
    for name, func in (("prepare", prepare), ("execute", execute), ("preflight", preflight)):
        s = sub.add_parser(name)
        s.add_argument("--run-id", required=True)
        if name != "preflight":
            s.add_argument("--n", type=int, default=500)
            s.add_argument("--seed", type=int, default=20260711)
            s.add_argument("--best-of", type=int, default=4)
            s.add_argument("--temperature", type=float, default=0.7)
            s.add_argument("--max-new", type=int, default=512)
        if name == "execute":
            s.add_argument("--fixture", action="store_true")
        s.set_defaults(func=func)
    return p


if __name__ == "__main__":
    args = parser().parse_args()
    if hasattr(args, "n") and (args.n <= 0 or args.best_of != 4 or args.max_new < 32):
        raise SystemExit("require n>0, best-of=4, and max-new>=32")
    args.func(args)
